spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  cloud:
    config:
      retry:
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
        max-attempts: 6
  datasource:
    url: jdbc:mysql://mysql:3306/basic_account
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
