spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basic_account
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082

eureka:
  client:
    enabled: true
    server-url:
      defaultZone: http://eureka-server:8761/eureka/
