
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: lb://CUSTOMER
              predicates:
                - Path=/customer/**

            - id: account-service
              uri: lb://ACCOUNT
              predicates:
                - Path=/account/**
server:
  port: 8080
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
