spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    config:
      retry:
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
        max-attempts: 6
  datasource:
    url: jdbc:mysql://mysql:3306/basic_customer
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
